services:
  backend-app:
    build: .
    volumes:
      - backend-app-v:/data
      - ./config.py:/backend_app/config.py
    depends_on:
      backend-app-db:
        condition: service_completed_successfully

  backend-app-db:
    build:
      context: .
      dockerfile_inline: |
        FROM alpine
        CMD ["touch", "/data/backend.db"]  
    volumes:
      - backend-app-v:/data

volumes:
  backend-app-v: